# Generated by Django 3.2 on 2021-05-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prueba',
            options={'ordering': ['-titulo'], 'verbose_name': 'Titulo', 'verbose_name_plural': 'Titulos de prueba'},
        ),
        migrations.AlterField(
            model_name='prueba',
            name='titulo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
